### PR TITLE
OME project dependency checks

### PR DESCRIPTION
**Pull request by chris-allan**
This is a start for restoring OMERO server support which was removed in #26. Since version 2.0.0 the *OMERO dependencies have been removed from the dependency tree. This has had the effective result of breaking the first-class support for OMERO in downstream CellProfiler.

Related discussion is in #33.

Some items to be looked at post this PR being merged:

 * opencsv `FIXME` should be investigated and addressed. If the `com.opencsv` dependency should actually be used then these changes should be made. The current XML block containing the `FIXME` has been commented out for 2 years.
 * ImageJ2 and imglib2 dependencies need some love. Why the ImageJ2 updater package is used a root dependency I am not 100% sure of the rationale for but it looks like at some point an attempt was made to ensure the dependency was updated via CellProfiler preferences. Furthermore, the currently defined `imagej-common` transitive dependency, via `imagej-updater`, for imglib2 is defined at version `3.2.0` whereas `2.0.0-beta-26` is currently explicitly defined. These packages evolve quite rapidly and the potential for API breakage as a result of these divergent versions is quite high. I can't really speak as to whether the test coverage is currently sufficient to attempt an upgrade of these dependencies with confidence.
 * Updating the parent POM is likely needed if the desire is to continue to use it. Incidentally, it is not clear to me that it is required and may actually be causing more trouble than it is worth. Sucking in the entirety of the scientific computing stack for Java is highly unlikely to be the desired outcome. The POM has its own dependency management strategy which should be reviewed [1]. `10.4.1` is almost 16 months old and there have been 20+ revisions since its release. `17.0.0` is current as of 2017-09-07.  There POM conformance issues that would need to be addressed in order to this or a later version.

1. https://github.com/scijava/pom-scijava/blob/pom-scijava-17.0.0/pom.xml#L112

### CODE REVIEW

**Comment by 0x00b1** [comment]
@chris-allan Yikes! Let’s fix this ASAP.

**Comment by chris-allan** [comment]
Agreed.

Do you know if the reason for the OMERO dependencies being dropped was conflicts?

If not I can take a stab at adding them back in, using the latest 5.3.x release, with as many appropriate excludes as possible.

**Comment by chris-allan** [comment]
Made significant changes to the POM in 044d91cbc501d928f5d96dcaf94e717147c63086 as related to Bio-Formats. This reverts a lot of specific dependency handling changed in #26 which would have made certain readers non-functional due to class not found exceptions and had removed other readers entirely.

I'm not 100% as to the rationale behind those changes but perhaps @mcquin can elaborate.

The current dependency tree is as follows:

```
$ mvn dependency:tree
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building prokaryote 2.3.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ prokaryote ---
[INFO] org.cellprofiler:prokaryote:jar:2.3.1
[INFO] +- org.apache.commons:commons-lang3:jar:3.5:compile
[INFO] +- ome:formats-gpl:jar:5.7.1:compile
[INFO] |  +- org.openmicroscopy:ome-common:jar:5.3.2:compile
[INFO] |  |  +- com.google.guava:guava:jar:18.0:compile
[INFO] |  |  +- ch.qos.logback:logback-core:jar:1.1.1:compile
[INFO] |  |  +- ch.qos.logback:logback-classic:jar:1.1.1:compile
[INFO] |  |  +- xalan:serializer:jar:2.7.2:runtime
[INFO] |  |  \- xalan:xalan:jar:2.7.2:runtime
[INFO] |  +- org.openmicroscopy:ome-xml:jar:5.5.4:compile
[INFO] |  +- ome:formats-bsd:jar:5.7.1:compile
[INFO] |  |  +- org.openmicroscopy:specification:jar:5.5.4:compile
[INFO] |  |  +- org.openmicroscopy:ome-codecs:jar:0.2.0:compile
[INFO] |  |  |  \- org.openmicroscopy:ome-jai:jar:0.1.0:compile
[INFO] |  |  +- ome:turbojpeg:jar:5.7.1:compile
[INFO] |  |  +- org.scijava:native-lib-loader:jar:2.1.3:compile
[INFO] |  |  +- com.jgoodies:jgoodies-forms:jar:1.7.2:compile
[INFO] |  |  |  \- com.jgoodies:jgoodies-common:jar:1.7.0:compile
[INFO] |  |  +- org.perf4j:perf4j:jar:0.9.13:compile
[INFO] |  |  \- com.drewnoakes:metadata-extractor:jar:2.6.2:compile
[INFO] |  |     +- com.adobe.xmp:xmpcore:jar:5.1.2:compile
[INFO] |  |     \- xerces:xercesImpl:jar:2.8.1:compile
[INFO] |  +- ome:formats-api:jar:5.7.1:compile
[INFO] |  +- org.openmicroscopy:ome-mdbtools:jar:5.3.0:compile
[INFO] |  +- org.openmicroscopy:metakit:jar:5.3.0:compile
[INFO] |  +- org.openmicroscopy:ome-poi:jar:5.3.1:compile
[INFO] |  |  \- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  +- ome:jxrlib-all:jar:0.2.1:compile
[INFO] |  +- edu.ucar:netcdf:jar:4.3.22:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.6:compile
[INFO] |  +- woolz:JWlz:jar:1.4.0:compile
[INFO] |  +- joda-time:joda-time:jar:2.3:compile
[INFO] |  +- com.esotericsoftware.kryo:kryo:jar:2.24.0:compile
[INFO] |  |  +- com.esotericsoftware.minlog:minlog:jar:1.2:compile
[INFO] |  |  \- org.objenesis:objenesis:jar:2.1:compile
[INFO] |  \- ch.systems.cisd:jhdf5:jar:14.12.0:compile
[INFO] +- org.glassfish:javax.json:jar:1.1:compile
[INFO] +- au.com.bytecode:opencsv:jar:2.4:compile
[INFO] +- net.imglib2:imglib2-meta:jar:2.0.0-beta-26:compile
[INFO] |  +- net.imglib2:imglib2:jar:2.0.0-beta-26:compile
[INFO] |  +- org.scijava:scijava-common:jar:2.56.0:compile
[INFO] |  |  +- org.scijava:scijava-expression-parser:jar:3.0.1:compile
[INFO] |  |  +- com.googlecode.gentyref:gentyref:jar:1.1.0:compile
[INFO] |  |  \- org.bushe:eventbus:jar:1.4:compile
[INFO] |  \- edu.ucar:udunits:jar:4.3.18:compile
[INFO] +- net.imagej:imagej-updater:jar:0.8.3:compile
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- net.imagej:imagej-common:jar:0.24.4:compile
[INFO] \- xml-apis:xml-apis:jar:xerces-2.7.1:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.774 s
[INFO] Finished at: 2017-09-25T14:42:16+01:00
[INFO] Final Memory: 21M/217M
[INFO] ------------------------------------------------------------------------
```

**Comment by chris-allan** [comment]
Made significant changes to the POM as they related to ImageJ2 in 3423f66567b2d01d71ef3101025d278c7b367e5f.

Again, not 100% as to the original rationale in #26. In particular the dependency on `imagej-updater` seems rather strange and I'm not particularly sure as to why `imglib2-roi` is being excluded. Furthermore, the version mismatches between components here feel very odd and potentially breaking.

Current dependency tree is as follows:

```
$ mvn dependency:tree
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building prokaryote 2.3.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ prokaryote ---
[INFO] org.cellprofiler:prokaryote:jar:2.3.1
[INFO] +- org.apache.commons:commons-lang3:jar:3.5:compile
[INFO] +- ome:formats-gpl:jar:5.7.1:compile
[INFO] |  +- org.openmicroscopy:ome-common:jar:5.3.2:compile
[INFO] |  |  +- com.google.guava:guava:jar:18.0:compile
[INFO] |  |  +- ch.qos.logback:logback-core:jar:1.1.1:compile
[INFO] |  |  +- ch.qos.logback:logback-classic:jar:1.1.1:compile
[INFO] |  |  +- xalan:serializer:jar:2.7.2:runtime
[INFO] |  |  |  \- xml-apis:xml-apis:jar:1.3.04:runtime
[INFO] |  |  \- xalan:xalan:jar:2.7.2:runtime
[INFO] |  +- org.openmicroscopy:ome-xml:jar:5.5.4:compile
[INFO] |  +- ome:formats-bsd:jar:5.7.1:compile
[INFO] |  |  +- org.openmicroscopy:specification:jar:5.5.4:compile
[INFO] |  |  +- org.openmicroscopy:ome-codecs:jar:0.2.0:compile
[INFO] |  |  |  \- org.openmicroscopy:ome-jai:jar:0.1.0:compile
[INFO] |  |  +- ome:turbojpeg:jar:5.7.1:compile
[INFO] |  |  +- org.scijava:native-lib-loader:jar:2.1.3:compile
[INFO] |  |  +- com.jgoodies:jgoodies-forms:jar:1.7.2:compile
[INFO] |  |  |  \- com.jgoodies:jgoodies-common:jar:1.7.0:compile
[INFO] |  |  +- org.perf4j:perf4j:jar:0.9.13:compile
[INFO] |  |  \- com.drewnoakes:metadata-extractor:jar:2.6.2:compile
[INFO] |  |     +- com.adobe.xmp:xmpcore:jar:5.1.2:compile
[INFO] |  |     \- xerces:xercesImpl:jar:2.8.1:compile
[INFO] |  +- ome:formats-api:jar:5.7.1:compile
[INFO] |  +- org.openmicroscopy:ome-mdbtools:jar:5.3.0:compile
[INFO] |  +- org.openmicroscopy:metakit:jar:5.3.0:compile
[INFO] |  +- org.openmicroscopy:ome-poi:jar:5.3.1:compile
[INFO] |  |  \- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  +- ome:jxrlib-all:jar:0.2.1:compile
[INFO] |  +- edu.ucar:netcdf:jar:4.3.22:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.6:compile
[INFO] |  +- woolz:JWlz:jar:1.4.0:compile
[INFO] |  +- joda-time:joda-time:jar:2.3:compile
[INFO] |  +- com.esotericsoftware.kryo:kryo:jar:2.24.0:compile
[INFO] |  |  +- com.esotericsoftware.minlog:minlog:jar:1.2:compile
[INFO] |  |  \- org.objenesis:objenesis:jar:2.1:compile
[INFO] |  \- ch.systems.cisd:jhdf5:jar:14.12.0:compile
[INFO] +- org.glassfish:javax.json:jar:1.1:compile
[INFO] +- au.com.bytecode:opencsv:jar:2.4:compile
[INFO] +- net.imglib2:imglib2-meta:jar:2.0.0-beta-26:compile
[INFO] |  +- net.imglib2:imglib2:jar:2.0.0-beta-26:compile
[INFO] |  +- org.scijava:scijava-common:jar:2.56.0:compile
[INFO] |  |  +- org.scijava:scijava-expression-parser:jar:3.0.1:compile
[INFO] |  |  +- com.googlecode.gentyref:gentyref:jar:1.1.0:compile
[INFO] |  |  \- org.bushe:eventbus:jar:1.4:compile
[INFO] |  \- edu.ucar:udunits:jar:4.3.18:compile
[INFO] +- net.imagej:imagej-updater:jar:0.8.3:compile
[INFO] |  \- net.imagej:imagej-common:jar:0.24.1:compile
[INFO] \- junit:junit:jar:4.12:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.848 s
[INFO] Finished at: 2017-09-25T15:22:51+01:00
[INFO] Final Memory: 22M/217M
[INFO] ------------------------------------------------------------------------
```

/cc @mcquin

**Comment by mcquin** [comment]
@chris-allan I incorrectly removed the OME server dependency because I didn't find it was used in the code base. At the time, I didn't recognize this was the basis for OMERO/CellProfiler interactions. Thanks for adding a test!

Many of the exclusions were made as an attempt to circumvent warnings about twice defined libraries when building the package with `mvn package`. I hadn't seen any failures in reading BioFormats supported extensions since the change, but the image formats I and the assay developers in our group encounter certainly aren't comprehensive.

Thanks for your help in fixing the POM for this package. I'm afraid I am very inexperienced at packaging Java and I have a lot to learn.

**Comment by chris-allan** [comment]
Completely understandable, @mcquin. Updating the OMERO dependencies would have been a bear anyway. The upstream `org.scijava` POM is quite anal about duplicate classes.

As of ad2bb38dc8e5484341bf4b6ffee87bafee96442e OMERO support should be restored.  You will see from the exclude list that this is far from trivial to work with. The whole OME team is working a lot on simplifying all of this in the near future. Thankfully we have already done a lot of the work in `glencoesoftware/omero-ms-core` to understand the correct set of dependency exclusions when including the `blitz` dependency.

Sorting out the ImageJ2 and imglib2 dependencies more thoroughly is probably outside the scope of this PR as things stand.

There should be no warnings of duplicate library definitions during build with this PR. Let me know if you see any.

Current dependency tree is as follows:

```
$ mvn dependency:tree
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building prokaryote 2.3.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ prokaryote ---
[INFO] org.cellprofiler:prokaryote:jar:2.3.1
[INFO] +- org.apache.commons:commons-lang3:jar:3.5:compile
[INFO] +- ome:formats-gpl:jar:5.7.1:compile
[INFO] |  +- org.openmicroscopy:ome-common:jar:5.3.2:compile
[INFO] |  |  +- com.google.guava:guava:jar:18.0:compile
[INFO] |  |  +- ch.qos.logback:logback-core:jar:1.1.1:compile
[INFO] |  |  +- ch.qos.logback:logback-classic:jar:1.1.1:compile
[INFO] |  |  +- xalan:serializer:jar:2.7.2:runtime
[INFO] |  |  |  \- xml-apis:xml-apis:jar:1.3.04:runtime
[INFO] |  |  \- xalan:xalan:jar:2.7.2:runtime
[INFO] |  +- org.openmicroscopy:ome-xml:jar:5.5.4:compile
[INFO] |  +- ome:formats-bsd:jar:5.7.1:compile
[INFO] |  |  +- org.openmicroscopy:specification:jar:5.5.4:compile
[INFO] |  |  +- org.openmicroscopy:ome-codecs:jar:0.2.0:compile
[INFO] |  |  |  \- org.openmicroscopy:ome-jai:jar:0.1.0:compile
[INFO] |  |  +- ome:turbojpeg:jar:5.7.1:compile
[INFO] |  |  +- org.scijava:native-lib-loader:jar:2.1.3:compile
[INFO] |  |  +- com.jgoodies:jgoodies-forms:jar:1.7.2:compile
[INFO] |  |  |  \- com.jgoodies:jgoodies-common:jar:1.7.0:compile
[INFO] |  |  +- org.perf4j:perf4j:jar:0.9.13:compile
[INFO] |  |  \- com.drewnoakes:metadata-extractor:jar:2.6.2:compile
[INFO] |  |     +- com.adobe.xmp:xmpcore:jar:5.1.2:compile
[INFO] |  |     \- xerces:xercesImpl:jar:2.8.1:compile
[INFO] |  +- ome:formats-api:jar:5.7.1:compile
[INFO] |  +- org.openmicroscopy:ome-mdbtools:jar:5.3.0:compile
[INFO] |  +- org.openmicroscopy:metakit:jar:5.3.0:compile
[INFO] |  +- org.openmicroscopy:ome-poi:jar:5.3.1:compile
[INFO] |  |  \- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  +- ome:jxrlib-all:jar:0.2.1:compile
[INFO] |  +- edu.ucar:netcdf:jar:4.3.22:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.6:compile
[INFO] |  +- woolz:JWlz:jar:1.4.0:compile
[INFO] |  +- joda-time:joda-time:jar:2.3:compile
[INFO] |  +- com.esotericsoftware.kryo:kryo:jar:2.24.0:compile
[INFO] |  |  +- com.esotericsoftware.minlog:minlog:jar:1.2:compile
[INFO] |  |  \- org.objenesis:objenesis:jar:2.1:compile
[INFO] |  \- ch.systems.cisd:jhdf5:jar:14.12.0:compile
[INFO] +- omero:blitz:jar:5.3.4-ice36-b69:compile
[INFO] |  +- omero:server:jar:5.3.4-ice36-b69:compile
[INFO] |  |  +- omero:rendering:jar:5.3.4-ice36-b69:compile
[INFO] |  |  |  \- omero:romio:jar:5.3.4-ice36-b69:compile
[INFO] |  |  |     \- omero:common:jar:5.3.4-ice36-b69:compile
[INFO] |  |  |        \- omero:model-psql:jar:5.3.4-ice36-b69:compile
[INFO] |  |  \- edu.ucar:bufr:jar:1.1.00:compile
[INFO] |  +- com.zeroc:ice:jar:3.6.3:compile
[INFO] |  \- com.zeroc:glacier2:jar:3.6.3:compile
[INFO] +- org.glassfish:javax.json:jar:1.1:compile
[INFO] +- au.com.bytecode:opencsv:jar:2.4:compile
[INFO] +- net.imglib2:imglib2-meta:jar:2.0.0-beta-26:compile
[INFO] |  +- net.imglib2:imglib2:jar:2.0.0-beta-26:compile
[INFO] |  +- org.scijava:scijava-common:jar:2.56.0:compile
[INFO] |  |  +- org.scijava:scijava-expression-parser:jar:3.0.1:compile
[INFO] |  |  +- com.googlecode.gentyref:gentyref:jar:1.1.0:compile
[INFO] |  |  \- org.bushe:eventbus:jar:1.4:compile
[INFO] |  \- edu.ucar:udunits:jar:4.3.18:compile
[INFO] +- net.imagej:imagej-updater:jar:0.8.3:compile
[INFO] |  \- net.imagej:imagej-common:jar:0.24.1:compile
[INFO] \- junit:junit:jar:4.12:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.801 s
[INFO] Finished at: 2017-09-25T17:06:07+01:00
[INFO] Final Memory: 20M/217M
[INFO] ------------------------------------------------------------------------
```

**Comment by chris-allan** [comment]
Last couple cleanup commits added. Added a checklist of things to address separately to the PR description.

Final, I hope, dependency tree is as follows:

```
$ mvn dependency:tree
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building prokaryote 2.3.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ prokaryote ---
[INFO] org.cellprofiler:prokaryote:jar:2.3.1
[INFO] +- org.apache.commons:commons-lang3:jar:3.5:compile
[INFO] +- ome:formats-gpl:jar:5.7.1:compile
[INFO] |  +- org.openmicroscopy:ome-common:jar:5.3.2:compile
[INFO] |  |  +- com.google.guava:guava:jar:18.0:compile
[INFO] |  |  +- ch.qos.logback:logback-core:jar:1.1.1:compile
[INFO] |  |  +- ch.qos.logback:logback-classic:jar:1.1.1:compile
[INFO] |  |  +- xalan:serializer:jar:2.7.2:runtime
[INFO] |  |  |  \- xml-apis:xml-apis:jar:1.3.04:runtime
[INFO] |  |  \- xalan:xalan:jar:2.7.2:runtime
[INFO] |  +- org.openmicroscopy:ome-xml:jar:5.5.4:compile
[INFO] |  +- ome:formats-bsd:jar:5.7.1:compile
[INFO] |  |  +- org.openmicroscopy:specification:jar:5.5.4:compile
[INFO] |  |  +- org.openmicroscopy:ome-codecs:jar:0.2.0:compile
[INFO] |  |  |  \- org.openmicroscopy:ome-jai:jar:0.1.0:compile
[INFO] |  |  +- ome:turbojpeg:jar:5.7.1:compile
[INFO] |  |  +- org.scijava:native-lib-loader:jar:2.1.3:compile
[INFO] |  |  +- org.perf4j:perf4j:jar:0.9.13:compile
[INFO] |  |  \- com.drewnoakes:metadata-extractor:jar:2.6.2:compile
[INFO] |  |     +- com.adobe.xmp:xmpcore:jar:5.1.2:compile
[INFO] |  |     \- xerces:xercesImpl:jar:2.8.1:compile
[INFO] |  +- ome:formats-api:jar:5.7.1:compile
[INFO] |  +- org.openmicroscopy:ome-mdbtools:jar:5.3.0:compile
[INFO] |  +- org.openmicroscopy:metakit:jar:5.3.0:compile
[INFO] |  +- org.openmicroscopy:ome-poi:jar:5.3.1:compile
[INFO] |  |  \- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  +- ome:jxrlib-all:jar:0.2.1:compile
[INFO] |  +- edu.ucar:netcdf:jar:4.3.22:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.6:compile
[INFO] |  +- woolz:JWlz:jar:1.4.0:compile
[INFO] |  +- joda-time:joda-time:jar:2.3:compile
[INFO] |  +- com.esotericsoftware.kryo:kryo:jar:2.24.0:compile
[INFO] |  |  +- com.esotericsoftware.minlog:minlog:jar:1.2:compile
[INFO] |  |  \- org.objenesis:objenesis:jar:2.1:compile
[INFO] |  \- ch.systems.cisd:jhdf5:jar:14.12.0:compile
[INFO] +- omero:blitz:jar:5.3.4-ice36-b69:compile
[INFO] |  +- omero:server:jar:5.3.4-ice36-b69:compile
[INFO] |  |  \- omero:rendering:jar:5.3.4-ice36-b69:compile
[INFO] |  |     \- omero:romio:jar:5.3.4-ice36-b69:compile
[INFO] |  |        \- omero:common:jar:5.3.4-ice36-b69:compile
[INFO] |  |           \- omero:model-psql:jar:5.3.4-ice36-b69:compile
[INFO] |  +- com.zeroc:ice:jar:3.6.3:compile
[INFO] |  \- com.zeroc:glacier2:jar:3.6.3:compile
[INFO] +- org.glassfish:javax.json:jar:1.1:compile
[INFO] +- au.com.bytecode:opencsv:jar:2.4:compile
[INFO] +- net.imglib2:imglib2-meta:jar:2.0.0-beta-26:compile
[INFO] |  +- net.imglib2:imglib2:jar:2.0.0-beta-26:compile
[INFO] |  +- org.scijava:scijava-common:jar:2.56.0:compile
[INFO] |  |  +- org.scijava:scijava-expression-parser:jar:3.0.1:compile
[INFO] |  |  +- com.googlecode.gentyref:gentyref:jar:1.1.0:compile
[INFO] |  |  \- org.bushe:eventbus:jar:1.4:compile
[INFO] |  \- edu.ucar:udunits:jar:4.3.18:compile
[INFO] +- net.imagej:imagej-updater:jar:0.8.3:compile
[INFO] |  \- net.imagej:imagej-common:jar:0.24.1:compile
[INFO] \- junit:junit:jar:4.12:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.817 s
[INFO] Finished at: 2017-09-26T08:32:56+01:00
[INFO] Final Memory: 19M/217M
[INFO] ------------------------------------------------------------------------
```

**Comment by 0x00b1** [comment]
Thanks, @chris-allan! This is fantastic.

**Comment by lguerard** [comment]
Hi guys, 

I was wondering if you guys had a link to a .jar file to test if the LoadData module is able to access OMERO 5.3 images ?

We have a user waiting for that connection to be fixed so that would help a lot.

Thanks for your help.

**Comment by chris-allan** [comment]
Once the CellProfiler team mints a new version of the Prokaryote Python dependency you should have a JAR accessible @lguerard. 

However, If you want something very quickly you can clone this repository and run `mvn package` to get yourself a `prokaryote.jar` in `target/` that you can test with.

**Comment by lguerard** [comment]
Thanks @chris-allan for the help.

I ran `mvn package` in the cloned folder but got 4 different jar then, one `original-prokaryote-2.3.1`, one `prokaryote-2.3.1`, one `prokaryote-2.3.1-sources` and a `prokaryote-2.3.1-tests`.

I tried replacing the current `prokaryote.jar` with the 2.3.1 but ended up getting an error when starting CellProfiler.
`Exception in thread "main" java.lang.ClassNotFoundException: net.imagej.patcher.JavaAgent
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:304)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
FATAL ERROR in native method: processing of -javaagent failed
Aborted
`

I'm really sorry to be not knowledgeable about that..

**Comment by mcquin** [comment]
@lguerard I think you're only missing the last step here:

```
mvn package
cp target/prokaryote-2.3.1.jar .
pip install --upgrade --editable .
```

**Comment by chris-allan** [comment]
The problem there actually appears to be that the `net.imagej.patcher.JavaAgent` class, which is part of the ImageJ1 patcher, is being referred to somewhere but is not on the classpath. Which it is, in the JAR manifest. It seems like the idea was to preload the class prior to the main method being invoked but the rationale for that is foggy at best.

It was originally done in PR #10 as an attempt to fix issue #9 but it's not clear to me that it was actually effective. My read is that @0x00b1 closed #9 effectively as "wontfix" due to ImageJ support being dropped.

The references to the `ij1-patcher` dependency which contains the `net.imagej.patcher.JavaAgent` class have been removed for some time. I've opened #37 to remove this reference from the POM which will hopefully clear this error up for @lguerard.

**Comment by lguerard** [comment]
Thanks a lot for your helps guys. I was able to get the jar file and install it.

However, I still get an error when trying to use the LoadData module. It says Failed to log on server and this is the error visible in the terminal.

```
Traceback (most recent call last):
  File "/home/laurent/Softs/CellProfiler/cellprofiler/gui/pipelinecontroller.py", line 2826, in do_step
    self.__pipeline.run_module(module, workspace)
  File "/home/laurent/Softs/CellProfiler/cellprofiler/pipeline.py", line 2067, in run_module
    module.run(workspace)
  File "/home/laurent/Softs/CellProfiler/cellprofiler/modules/loaddata.py", line 1069, in run
    image = image_set.get_image(image_name)
  File "/home/laurent/Softs/CellProfiler/cellprofiler/measurements.py", line 1616, in get_image
    image = matching_providers[0].provide_image(self)
  File "/home/laurent/Softs/CellProfiler/cellprofiler/modules/loadimages.py", line 3201, in provide_image
    self.cache_file()
  File "/home/laurent/Softs/CellProfiler/cellprofiler/modules/loadimages.py", line 3110, in cache_file
    rdr = get_image_reader(id(self), url=url)
  File "/usr/local/lib/python2.7/dist-packages/bioformats/formatreader.py", line 945, in get_image_reader
    rdr = ImageReader(path=path, url=url)
  File "/usr/local/lib/python2.7/dist-packages/bioformats/formatreader.py", line 586, in __init__
    je, "loci/formats/FormatException"):
  File "/home/laurent/.local/lib/python2.7/site-packages/javabridge/jutil.py", line 806, in is_instance_of
    raise JavaException(jexception)
JavaException: loci/formats/FormatException
```

**Comment by ehrenfeu** [comment]
Guys, we (@lguerard and myself) are unfortunately really stuck here and getting somewhat desperate... Is there anything we can do to get the CP-OMERO bridge running with our OMERO 5.3?

**Comment by chris-allan** [comment]
I'll be trying to look at this in more detail in the next week or so. The above comments, and probably at least one PR do need to be merged and/or looked at more seriously.

In order to do any of this what I'm going to need to understand what you're deploying and how @lguerard and @ehrenfeu. At a minimum what I need to know is:

 * CP 2.2.x? 3.x?
 * `prokaryote` installed how?
 * What does your pipeline look like?

/cc @0x00b1, @mcquin, @emilroz

**Comment by lguerard** [comment]
Hi @chris-allan, 

Thanks for the help.

- So far, I tried with CP 2.2.0 and 3.0.0 with the same `failed to login` error.

- For Prokaryote, I followed @mcquin message using maven first then pip installing.

- And any pipeline really, even just one with the `LoadData` module to just check the connection fails.

**Comment by chris-allan** [comment]
I have opened #37 which restores CellProfiler 2.2.x compatibility. Will add details for 2.2.x and 3.x usage to #33.

**Pull request merged**
